service: sst-guide-ext-api-identity

plugins:
  - serverless-bundle
  - serverless-offline

custom: ${file(../../serverless.common.yml):custom}

package:
  individually: true

provider:
  name: aws
  runtime: nodejs12.x
  stackTags:
    project: ${self:custom.project}
    stack: ${self:service}
  tags:
    project: ${self:custom.project}
    stack: ${self:service}
  stage: dev
  region: us-east-1
  tracing:
    lambda: true

  apiGateway:
    restApiId: !ImportValue ${self:custom.stage}-ExtApiGatewayRestApiId
    restApiRootResourceId: !ImportValue ${self:custom.stage}-ExtApiGatewayRestApiRootResourceId

functions:
  # Defines an HTTP API endpoint that calls the main function in billing.js
  # - path: url path is /billing
  # - method: POST request
  identityId:
    handler: identityId.main
    events:
      - http:
          path: identity-id
          method: get
          cors: true
          authorizer: aws_iam
